{% set version = "3.2.4" %}

package:
  name: gdcm-split
  version: {{ version }}

source:
  url: https://github.com/malaterre/GDCM/archive/v{{ version }}.tar.gz
  fn: GDCM-{{ version }}.tar.gz
  sha256: 7f4a039613b428ab2f8235867d1f450b5827d476f9ddd422783eb05d7366b89c
  patches:
    - swig.patch

build:
  number: 0

requirements:
  build:
    - cmake
    - ninja
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - pkg-config             # [unix]
    - swig
  host:
    - python
    - libuuid  # [unix]
    - zlib
    - openjpeg
    - expat
    - json-c
    - libpython  # [win]
    - libjpeg-turbo

outputs:
  - name: libgdcm
    script: libgdcm_install.sh   # [not win]
    script: libgdcm_install.bat  # [win]
    requirements:
      build:
        - cmake
      host:
        - libuuid  # [unix]
        - zlib
        - openjpeg
        - expat
        - json-c
        - libjpeg-turbo
      run:
        - json-c
    test:
      commands:
        - test -f $PREFIX/lib/libgdcmCommon.so.3.2       # [linux]
        - test -f $PREFIX/lib/libgdcmCommon.3.2.dylib  # [osx]
        - test -f $PREFIX/share/gdcm-3.2/XML/Part3.xml               # [unix]
        - if not exist %LIBRARY_BIN%\\gdcmCommon.dll exit 1          # [win]

  - name: libgdcm-devel
    script: libgdcm-devel_install.sh   # [not win]
    script: libgdcm-devel_install.bat  # [win]
    build:
      run_exports:
        - {{ pin_subpackage('libgdcm', max_pin='x.x') }}
    requirements:
      build:
        - cmake
      host:
        - {{ pin_subpackage('libgdcm', exact=True) }}
      run:
        - {{ pin_subpackage('libgdcm', exact=True) }}
    test:
      commands:
        - test -d $PREFIX/include/gdcm-3.2                            # [unix]
        - test -f $PREFIX/lib/gdcm-3.2/GDCMConfig.cmake              # [unix]
        - if not exist %LIBRARY_INC%\\gdcm-3.2 exit 1                # [win]

  - name: gdcm
    script: gdcm_install.sh   # [not win]
    script: gdcm_install.bat  # [win]
    requirements:
      build:
        - cmake
      host:
        - python
        - {{ pin_subpackage('libgdcm', exact=True) }}
      run:
        - python
        - {{ pin_subpackage('libgdcm', exact=True) }}
    test:
      commands:
        - python -c "import gdcm"

about:
  home: https://sourceforge.net/p/gdcm/gdcm/
  license: BSD-2-Clause
  license_file: Copyright.txt
  summary: Grassroots DICOM, cross-platform DICOM implementation.

extra:
  recipe-maintainers:
    - mariusvniekerk
